# Generated by Django 4.1.2 on 2022-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwapp', '0002_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('immg', models.ImageField(upload_to='immags')),
                ('dec', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='uploadphoto',
            name='img',
            field=models.ImageField(upload_to='imags'),
        ),
    ]
